name: aktiendepot.pro
tagline:
url: http://www.aktiendepot.pro


markdown: kramdown

kramdown:
  auto_ids: true
  parse_block_html: true

plugins:

exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock

collections:
  brokers:
    output: true